### ISSUE TITLE
LT: Open file first, close file last

### ISSUE THREAD

**Issue by logan-yliniemi** [Jeremy-Fries/MAP-Elites-v1#8]
(Long Term)
Within our scope, the most expensive single operation that happens in an executable is the opening and closing of a text file. Doing this at every time step will be prohibitively slow. Instead, if we can open the files early, store what we want into a vector, write the vector all at once, and then close them at the end, this is more ideal.

Alternate solution: It's possible that in the ifstream/ofstream framework this is not the case, but we would need to test both ways to ensure we aren't slowing ourselves down unnecessarily.

Alternate solution 2: After we get the code integrated, profiling the run time will tell us if this is a serious contribution to our run time or not.

**Comment by sierrasaurous** [comment]
As the code stands now, the file should be opening at the beginning of a simulation, and closing at the end, as opposed to each time step. I will look into appending to a file as opposed to wiping the file, so that we can output multiple simulations into one file.

Another option would be to open and close the file elsewhere in the code, but then the file would need to be passed around and might not be beneficial.
